apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mydemo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "<repo URL starts with 'https' or 'git@github.com'>"
    path: "helm-guestbook"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default