# Child application for prometheus, within templates in apps folder
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.10.0
      helm:
        valueFiles:
        - $values/efk/es-myvalues.yaml
    - repoURL: https://github.com/ozlia/app_of_apps.git
      targetRevision: main
      ref: values  
    - repoURL: https://helm.elastic.co
      chart: kibana
      targetRevision: 8.10.0
      helm:
        valueFiles:
        - $values/efk/kibana-myvalues.yml
  syncPolicy:
    automated:
      prune: true # or false, depending on your needs
      selfHeal: true # or false, based on preference   
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: efk